#!/usr/bin/env bash
# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
set -ex

DEPS_DIR="$(dirname $0)/deps"

# Detect distro from /etc/os-release
if [ -f /etc/os-release ]; then
    . /etc/os-release
else
    echo >&2 "ERROR: /etc/os-release not found. Cannot detect distribution."
    exit 1
fi

case "$ID" in
    ubuntu|debian)
        "$DEPS_DIR/install-x86_64-debs"
        ;;
    arch)
        "$DEPS_DIR/install-x86_64-arch"
        ;;
    *)
        echo >&2 "ERROR: Unsupported distribution '$ID'. Supported: ubuntu, debian, arch."
        exit 1
        ;;
esac

"$DEPS_DIR/install-x86_64-other"

Red='\033[0;31m'
Reset='\033[0m'
# Check if submodules were initialized. If a submodule is not initialized, git
# submodule status will be prefixed with `-`
if git submodule status | grep '^-'; then
    echo >&2 -e "${Red}ERROR${Reset}: Git modules were not initialized. Run 'git submodule update --init' to initialize them."
fi
